### ISSUE TITLE
Streaming at highest color resolution

### ISSUE THREAD

**Issue by RaduCorcodel** [Kinovarobotics/ros_kortex_vision#12]
Hi,

I'm trying to roslaunch the color_only node with ```roslaunch kinova_vision kinova_vision_color_only.launch color_camera_info_url:=file:///homes/corcodel/ws_kortex/src/ros_kortex_vision/launch/calibration/default_color_calib_1920x1080.ini``` but I'm getting the message

```
[ WARN] [1658266356.621532826]: [color]: Calibration file sensor resolution (1080x1920 pixels) doesn't match stream resolution (720x1280 pixels)
```

which is not unexpected since I didn't specify anywhere the resolution that I want. Can you please tell me where do I set it the resolution? Neither launchers have the launch arguments to set the resolution.

Thank you.

Radu,

**Comment by felixmaisonneuve** [comment]
Hi @RaduCorcodel,

you can change it using the Web app (in the Configuration page)
![image](https://user-images.githubusercontent.com/83971099/180007546-b120418c-534e-48af-a40c-a6e139b476cf.png)

You can also use the API by using `SetSensorSettings` in the [VisionConfig](https://github.com/Kinovarobotics/kortex/blob/master/api_cpp/doc/markdown/summary_pages/VisionConfig.md). You can specify the resolution in your [SensorSettings](https://github.com/Kinovarobotics/kortex/blob/master/api_cpp/doc/markdown/messages/VisionConfig/SensorSettings.md#). Here is the [Resolution Enum](https://github.com/Kinovarobotics/kortex/blob/master/api_cpp/doc/markdown/enums/VisionConfig/Resolution.md#)

Every API call is also autogenerated in ROS, so it should be possible to change the resolution in ROS as well. 

Regards,
Felix

**Comment by RaduCorcodel** [comment]
Perfect. Sure, I'll do it through a service call. The reference on how to do that is just a little lost in the weeds, maybe it wouldn't be a bad idea to mention it specifically. 
Thanks again. I'll close this.

Best,
Radu
