### ISSUE TITLE
Add ROS 2 Support

### ISSUE THREAD

**Issue by eholum** [Kinovarobotics/ros_kortex_vision#19]
Picking up from https://github.com/Kinovarobotics/ros_kortex_vision/issues/18

We have a functional migration of this package to ROS 2 in https://github.com/PickNikRobotics/ros2_kortex_vision/pull/1/. These changes will help ROS 2 developers using Kinova arms, alongside the updated ros2 kortex drivers in https://github.com/Kinovarobotics/ros2_kortex.

If possible, we would recommend creating a basic `ros2` branch in the official, Kinova owned repository and merging our changes here for wider consumption. Alternatively, we could create a `Kinovarobotics/ros2_kortex_vision` and merge the PickNik owned fork there.

Looking for guidance.

**Comment by martinleroux** [comment]
Hi @eholum ,

We have been preparing a vision demon in ROS2 for ICRA next month. We should be able to make it public after the show, but if you still need assistance with making the vision system work in ROS2, you may reach out to us at support@kinova.ca and we can assist you there.
