### ISSUE TITLE
How to get the cartesian position and rotation matrix corresponding to the robot base frame?

### ISSUE THREAD

**Issue by HeegerGao** [Kinovarobotics/ros_kortex_vision#7]
Hi, I'd like to know how to read the cartesian position and rotation matrix corresponding to the robot base frame. Is there any ros topic responsible for this, or can we calculate them from some other information? Thank you very much!

**Comment by felixmaisonneuve** [comment]
For anyone that have the same question, this issue was answered [here](https://github.com/Kinovarobotics/ros_kortex/issues/207)
